version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build_test:
    docker:
      - image: "cimg/python:<<parameters.tag>>"
    parameters:
      tag:
        default: "3.8"
        type: string
    steps:
      - checkout  # checkout source code to working directory
      - run: python --version
      - run: brew install pyenv
      - run:
          command: |  # create whl, install twine and publish to Test PyPI
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install twine
            pipenv run twine upload --repository testpypi dist/*


  test_pypi_publish:
    docker:
      - image: "cimg/python:3.8"
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl, install twine and publish to Test PyPI
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install twine
            pipenv run twine upload --repository testpypi dist/*
  pypi_publish:
    docker:
      - image: "cimg/python:3.8"
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl, install twine and publish to PyPI
            python setup.py sdist bdist_wheel
            python patch_version.py $CIRCLE_TAG
            sudo pip install pipenv
            pipenv install twine
            pipenv run twine upload dist/*
workflows:
  build_test_publish:
    jobs:
      - build_test
      - test_pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - develop
      - pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - main
